use crate::{EGraph, Expr, EClassId, OpId};
use std::str::FromStr;

grammar(egraph: &mut EGraph);

Num: i32 = r"[0-9]+" => i32::from_str(<>).unwrap();
Var: String = r"[[:alpha:]][[:word:]]*" => <>.into();


pub Term: EClassId = {
    Num => egraph.add(Expr::Const(<>)),
    Var => egraph.add(Expr::Var(<>)),
    "(" "+" <l:Term> <r:Term>")" => egraph.add(Expr::Op2(OpId(0), l, r)),
    "(" "*" <l:Term> <r:Term>")" => egraph.add(Expr::Op2(OpId(1), l, r)),
};
