use crate::expr::{Expr, Id, tests::{TestNode, Name}};

grammar(expr: &mut Expr<TestNode>);

Ident: Name = r"[a-zA-Z]+" => <>.into();
Symbol: Name = r"[+=\-*^&$%@!]+" => <>.into();

pub Term: Id = {
    Ident => expr.add(TestNode::Var(<>.into())),
    r"[0-9]+" => expr.add(TestNode::Const(<>.into())),
    "(" <op:Ident> <args:Term*> ")" => expr.add(TestNode::Op(op.into(), args)),
    "(" <op:Symbol> <args:Term*> ")" => expr.add(TestNode::Op(op.into(), args)),
};
